### PR TITLE
BIOX-2849: Emit checkpoints when changing infill to add to undo stack

### PR DESCRIPTION
**Pull request by jesper-cellink**

### CODE REVIEW

**Review by VDykyi — APPROVED** [review]

**Review by marcus-sonestedt — APPROVED** [review]
Looks good.

But you remove updateInfill() three times but only add it two times?  Just checking. :)

**Comment by jesper-cellink** [comment]
> Looks good.
> 
> But you remove updateInfill() three times but only add it two times? Just checking. :)

Yes, I had added it by mistake in those places when I implemented it. So just removing stuff that doesn't affect the behavior :)

**Comment by marcus-sonestedt** [comment]
> > But you remove updateInfill() three times but only add it two times? Just checking. :)
> 
> Yes, I had added it by mistake in those places when I implemented it. So just removing stuff that doesn't affect the behavior :)

Seems like same change was in @VDykyi 's PR too..

**Comment by VDykyi** [comment]
> > > But you remove updateInfill() three times but only add it two times? Just checking. :)
> > 
> > 
> > Yes, I had added it by mistake in those places when I implemented it. So just removing stuff that doesn't affect the behavior :)
> 
> Seems like same change was in @VDykyi 's PR too..

I integrated the Jesper's changes at night... After he created PR...

**Pull request merged**
