### PR TITLE
Replace qt foreach keyword for range-based loops

### PR DESCRIPTION
**Pull request by tcoyvwac**
As titled. 
This brings the codebase closer to native C++ standards and algorithms.

---
https://doc-snapshots.qt.io/qt6-dev/foreach-keyword.html
> Note: The foreach keyword was introduced before the C++11 range-based loops existed. New code should prefer C++11 range-based loops.

### CODE REVIEW

**Review by marcus-sonestedt — CHANGES_REQUESTED** [review]
Run in this in Qt Creator with clazy and add qAsConst(), and temporary refs, where required, to avoid containers detaching.

Qt's copy-on-write containers has some issues with range for.

**Comment by tcoyvwac** [comment]
Updated changeset to fix clazy warnings.

**Comment by tcoyvwac** [comment]
Hi, is there anything else needed / requested for this PR to be merged? I'm happy to close the PR and merge in my `origin` mirror if merging with (this) `upstream` is unfortunately not possible...

**Review by marcus-sonestedt — APPROVED** [review]

**Comment by marcus-sonestedt** [comment]
Sorry for not responding, Your last two comments got lost in the deluge of github emails I get related to work. :(   

Much appreciated!

**Pull request merged**
